name: gorest_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  dio: ^4.0.6
  equatable: ^2.0.5

dev_dependencies: 
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  mockito: ^5.3.2

flutter: 
  uses-material-design: true

