// Mocks generated by Mockito 5.3.2 from annotations
// in gorest_app/test/domain/features/user/repositories/i_user_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:gorest_app/domain/features/user/entities/pagination_entity.dart'
    as _i2;
import 'package:gorest_app/domain/features/user/entities/user_data_entity.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

import 'i_user_repository_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaginationEntity_0<T> extends _i1.SmartFake
    implements _i2.PaginationEntity<T> {
  _FakePaginationEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IUserRepositoryTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUserRepositoryTest extends _i1.Mock
    implements _i3.IUserRepositoryTest {
  MockIUserRepositoryTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PaginationEntity<_i5.UserDataEntity>> getUsers({
    int? page,
    int? perPage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [],
          {
            #page: page,
            #perPage: perPage,
          },
        ),
        returnValue: _i4.Future<_i2.PaginationEntity<_i5.UserDataEntity>>.value(
            _FakePaginationEntity_0<_i5.UserDataEntity>(
          this,
          Invocation.method(
            #getUsers,
            [],
            {
              #page: page,
              #perPage: perPage,
            },
          ),
        )),
      ) as _i4.Future<_i2.PaginationEntity<_i5.UserDataEntity>>);
  @override
  _i4.Future<_i5.UserDataEntity?> getUserDetail(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getUserDetail,
          [id],
        ),
        returnValue: _i4.Future<_i5.UserDataEntity?>.value(),
      ) as _i4.Future<_i5.UserDataEntity?>);
  @override
  _i4.Future<_i5.UserDataEntity?> addUser(_i5.UserDataEntity? userData) =>
      (super.noSuchMethod(
        Invocation.method(
          #addUser,
          [userData],
        ),
        returnValue: _i4.Future<_i5.UserDataEntity?>.value(),
      ) as _i4.Future<_i5.UserDataEntity?>);
  @override
  _i4.Future<_i5.UserDataEntity?> updateUser(
    int? id,
    _i5.UserDataEntity? userData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [
            id,
            userData,
          ],
        ),
        returnValue: _i4.Future<_i5.UserDataEntity?>.value(),
      ) as _i4.Future<_i5.UserDataEntity?>);
  @override
  _i4.Future<bool> deleteUser(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [id],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
